services:
  test-db:
    image: postgres:16-alpine
    container_name: thinhpay-test-db
    environment:
      POSTGRES_DB: thinhpay_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5435:5432" # Đổi từ 5434 thành 5435
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d thinhpay_test"]
      interval: 5s
      timeout: 5s
      retries: 5